### ISSUE TITLE
Split test report types into subpages

### ISSUE THREAD

**Issue by ironprogrammer** [WordPress/test-handbook#1]
This update follows the initial publication of the Test Reports page, [discussed in Make Test Slack](https://wordpress.slack.com/archives/C03B0H5J0/p1654798697162559?thread_ts=1654798408.140869&cid=C03B0H5J0). From the discussion:

> Move the [types of test reports (1-4)](https://make.wordpress.org/test/handbook/test-reports/#types-of-test-reports) into subpages under the primary Test Reports page, so the templates are more visible from the handbook nav.

Benefits:
- improve readability of individual test reports
- improve visibility of report types added to left navigation
- shorten the length of the Test Reports page
- provide canonical URLs for each type of report

**Comment by ironprogrammer** [comment]
Resolved with #12.

**Comment by ironprogrammer** [comment]
@oksanayoast, if you pass me your WordPress.org or Slack ID, I can offer official props. Thanks again!

**Comment by oksanayoast** [comment]
@ironprogrammer 
My wp.org username is `oksankaa` (https://profiles.wordpress.org/oksankaa/).
Thank you!
