### ISSUE TITLE
Request to Add 'Test Report' Plugin Link to the Sidebar of Test P2

### ISSUE THREAD

**Issue by ankitguptaindia** [WordPress/test-handbook#17]
Request for the addition of the ['Test Report' plugin](https://wordpress.org/plugins/test-reports/) link to the sidebar of https://make.wordpress.org/test/. This plugin is a valuable time-saver for contributors when updating Test Reports for core tickets, providing necessary information with just a few clicks.

Including the plugin link in the sidebar would enhance efficiency and save contributors time. 

**Location:** With other Testing Plugins in the sidebar widget. 

| Current Status | Expected |
|--------|--------|
| ![image](https://github.com/WordPress/test-handbook/assets/6384299/379b457c-3177-4a1d-a01c-e3b14e266ac1) | ![image](https://github.com/WordPress/test-handbook/assets/6384299/530afd9a-a16a-4f3b-8ac5-87b98c9f9cc9) |

**Comment by ironprogrammer** [comment]
Thanks for the suggestion, @ankitguptaindia! 🙌🏻 

The following updates have been applied to the [Test blog](https://make.wordpress.org/test/) sidebar:
- Added Test Reports plugin.
- Updated WPBT text to "WordPress Beta Tester" to match plugin name.
- Clarified beta plugins as "Other Beta Plugins".
- Updated Design Experiments link to official plugin page.
- Reordered links by priority (IMHO, and alternative ideas are welcome).

<img width="208" alt="updated Test blog sidebar links" src="https://github.com/user-attachments/assets/11ea23ba-e33c-4dcd-926b-ba2565869707">

**Comment by ankitguptaindia** [comment]
Thanks @ironprogrammer 🙏🏼
