### ISSUE TITLE
 Use a spider to crawl the test website

### ISSUE THREAD

**Issue by webtechpooja** [WordPress/test-handbook#23]
The step to use a [spider to crawl the test website](https://make.wordpress.org/test/2024/02/15/help-test-wordpress-6-5-beta-1/#:~:text=Run%20a%20spider%20against%20your%20site%20to%20process%20all%20the%20available%20pages), was seen within the list of things to do for release testing. The specific way to do it was not linked at that point, and hence, I thought this might help.

Google doc link- https://docs.google.com/document/d/1x2truDi9Ml9d7LedUVPgP_w_RqhtfTTE8fxn1ItyWO8/edit?usp=sharing

**Comment by webtechpooja** [comment]
This issue was discussed in the slack thread, this is link for reference - https://wordpress.slack.com/archives/C03B0H5J0/p1710242755542039

**Comment by nagpai** [comment]
I have made some updates, including adding details of using wget2 in the Google doc linked above.

**Comment by martinkrcho** [comment]
Thanks for the updates @nagpai. `wget2` and default theme data for import sound very reasonable.

The document looks like a good starting point. Let's publish it and make updates once there's some feedback from the community.

**Comment by kjnanda** [comment]
This would be really helpful if we get the visual explanation on how to use this! 🙇🏻‍♀️

**Comment by webtechpooja** [comment]
It is now in the handbook: https://make.wordpress.org/test/handbook/get-setup-for-testing/crawl-your-test-site-for-errors/
